version: "3.8"

services:
  mysql-pet:
    image: mysql:8.0
    container_name: mysql_pet_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pet123
      MYSQL_DATABASE: crud
    ports:
      - "3309:3306"
    volumes:
      - mysql_pet_data:/var/lib/mysql

volumes:
  mysql_pet_data: